=== ebi-uniprot/uniprot-core/xml-parser/src/main/resources/xsd/proteome.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified"
 targetNamespace="http://uniprot.org/proteome"  xmlns="http://uniprot.org/proteome" >
<xs:element name="proteomes">
		<xs:complexType>
			 <xs:annotation>
                       <xs:documentation>Describes a collection of proteome entries.</xs:documentation>
      	     </xs:annotation>
			<xs:sequence>
			        <xs:element ref="proteome" maxOccurs="unbounded"/>
	         </xs:sequence>
		</xs:complexType>
</xs:element>
 <xs:element name="proteome">
	<xs:complexType>
	 <xs:annotation>
            <xs:documentation>Describes proteome type.</xs:documentation>
        </xs:annotation>
			<xs:sequence>
			    <xs:element name="upid" type="xs:string" />
			    <xs:element name="description" type="xs:string" minOccurs="0"/>
			    <xs:element name="taxonomy" type="xs:long" />
			    <xs:element name="modified" type="xs:date" />
			    <xs:element name="isReferenceProteome" type="xs:boolean" />
			    <xs:element name="isRepresentativeProteome" type="xs:boolean" />
			    <xs:element name="redundantTo" type="xs:string" minOccurs="0"/>
			    <xs:element name="strain" type="xs:string" minOccurs="0"/>
			    <xs:element name="isolate" type="xs:string" minOccurs="0"/>
			    <xs:element name="genomeAssembly" type="genomeAssemblyType" minOccurs="0"/>
			    <xs:element name="genomeAnnotation" type="genomeAnnotationType" minOccurs="0"/>
				<xs:element name="component" type="componentType" maxOccurs="unbounded"/>
				<xs:element name="reference" type="referenceType" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element name="redundantProteome" type="redundantProteomeType" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element name="annotationScore" type="annotationScoreType" minOccurs="0"/>
				<xs:element name="panproteome" type="xs:string" minOccurs="0"/>
				<xs:element name="excluded" type="exclusionType" minOccurs="0"/>
				<xs:element name="scores" type="scoreType" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
		<xs:attribute name="proteinCount" type="xs:int"/>
   </xs:complexType>
   </xs:element>
   
    <xs:complexType name="genomeAssemblyType">
    <xs:sequence>
        <xs:element name="genomeAssemblySource" type="xs:string"/>
    	<xs:sequence minOccurs="0">
           <xs:element name="genomeAssembly" type="xs:string"/>
           <xs:element name="genomeAssemblyUrl" type="xs:string" minOccurs="0"/>
           <xs:element name="genomeRepresentation" type="xs:string" /> 
        </xs:sequence>
       </xs:sequence>
    </xs:complexType>
    
    <xs:complexType name="genomeAnnotationType">
    <xs:sequence>
       <xs:element name="genomeAnnotationSource" type="xs:string"/>
   		<xs:element name="genomeAnnotationUrl" type="xs:string" minOccurs="0" />
    </xs:sequence>
    </xs:complexType>
   
    <xs:complexType name="annotationScoreType">
         <xs:attribute name="normalizedAnnotationScore" type="xs:int" use="required"/>
    </xs:complexType>

    <xs:complexType name="redundantProteomeType">
    	<xs:annotation>
           <xs:documentation>
              Describes redundant proteome
           </xs:documentation>
        </xs:annotation>  
        <xs:attribute name="upid" type="xs:string" use="required"/>
        <xs:attribute name="similarity" type="xs:string" use="required"/>
    </xs:complexType>
	
   
	<xs:complexType name="componentType">
     	  <xs:sequence>
     	    <xs:element name="description" type="xs:string" minOccurs="0"/>
     	    <xs:element name="biosampleId" type="xs:string" minOccurs="0"/>
	        <xs:element name="genomeAccession" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
	        <xs:element name="genomeAnnotation" type="genomeAnnotationType" minOccurs="0"/>
     	  </xs:sequence>      
    	 <xs:attribute name="name" type="xs:string" use="required"/>
    	 <xs:attribute name="proteinCount" type="xs:int"/>
    </xs:complexType>
    
	  <!-- Reference definition begins -->
    <xs:complexType name="referenceType">
        <xs:annotation>
            <xs:documentation>Describes different types of citations.</xs:documentation>
        </xs:annotation>
        <xs:sequence>
            <xs:element name="citation" type="citationType"/>
        </xs:sequence>
    </xs:complexType>
    <!-- Reference definition ends -->
	  
    <!-- Citation definition begins -->
    <xs:complexType name="citationType">
        <xs:annotation>
            <xs:documentation>Describes different types of citations.</xs:documentation>
        </xs:annotation>
        <xs:sequence>
            <xs:element name="title" type="xs:string" minOccurs="0">
                <xs:annotation>
                    <xs:documentation>Describes the title of a citation.</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element name="authorList" type="nameListType" minOccurs="0">
                <xs:annotation>
                    <xs:documentation>Describes the authors of a citation.</xs:documentation>
                </xs:annotation>
            </xs:element>
              <xs:element name="dbReference" type="dbReferenceType" minOccurs="0" maxOccurs="unbounded">
                <xs:annotation>
                    <xs:documentation>Describes cross-references to bibliography databases (MEDLINE, PubMed, AGRICOLA) or other online resources (DOI).
                    Equivalent to the flat file RX-line.</xs:documentation>
                </xs:annotation>
            </xs:element>
                     
        </xs:sequence>
        <xs:attribute name="type" use="required">
            <xs:annotation>
                <xs:documentation>Describes the type of a citation.</xs:documentation>
            </xs:annotation>
            <xs:simpleType>
                <xs:restriction base="xs:string">
                    <xs:enumeration value="journal article"/>
                    <xs:enumeration value="submission"/>
                    <xs:enumeration value="book"/>
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
        <xs:attribute name="date">
            <xs:simpleType>
                <xs:union memberTypes="xs:date xs:gYearMonth xs:gYear"/>
            </xs:simpleType>
        </xs:attribute>
        <xs:attribute name="name" type="xs:string">
            <xs:annotation>
                <xs:documentation>Describes the name of an (online) journal or book.</xs:documentation>
            </xs:annotation>
        </xs:attribute>
        <xs:attribute name="volume" type="xs:string">
            <xs:annotation>
                <xs:documentation>Describes the volume of a journal or book.</xs:documentation>
            </xs:annotation>
        </xs:attribute>
        <xs:attribute name="first" type="xs:string">
            <xs:annotation>
                <xs:documentation>Describes the first page of an article.</xs:documentation>
            </xs:annotation>
        </xs:attribute>
        <xs:attribute name="last" type="xs:string">
            <xs:annotation>
                <xs:documentation>Describes the last page of an article.</xs:documentation>
            </xs:annotation>
        </xs:attribute>
        <xs:attribute name="db" type="xs:string">
            <xs:annotation>
                <xs:documentation>Describes the database name of submissions.</xs:documentation>
            </xs:annotation>
        </xs:attribute>        
    </xs:complexType>
    
    <xs:complexType name="consortiumType">
        <xs:annotation>
            <xs:documentation>Describes the authors of a citation when these are represented by a consortium.</xs:documentation>
        </xs:annotation>
        <xs:attribute name="name" type="xs:string" use="required"/>
    </xs:complexType>
    
    <xs:complexType name="personType">
        <xs:attribute name="name" type="xs:string" use="required"/>
    </xs:complexType>
    
    <xs:complexType name="nameListType">
        <xs:choice maxOccurs="unbounded">
            <xs:element name="consortium" type="consortiumType"/>
            <xs:element name="person" type="personType"/>
        </xs:choice>
    </xs:complexType>
    <!-- Citation definition ends -->

    <!-- Database cross-reference definition begins -->
    <xs:complexType name="dbReferenceType">
        <xs:annotation>
            <xs:documentation>Describes a database cross-reference.</xs:documentation>
        </xs:annotation>
        <xs:attribute name="type" type="xs:string" use="required">
            <xs:annotation>
                <xs:documentation>Describes the name of the database.</xs:documentation>
            </xs:annotation>
        </xs:attribute>
        <xs:attribute name="id" type="xs:string" use="required">
            <xs:annotation>
                <xs:documentation>Describes a unique database identifier.</xs:documentation>
            </xs:annotation>
        </xs:attribute>
    </xs:complexType>

   <xs:complexType name="exclusionType">
          <xs:sequence>
              <xs:element name="exclusionReason" type="xs:string" maxOccurs="unbounded"/>
          </xs:sequence>
   </xs:complexType>
   
     <xs:complexType name="scoreType">
          <xs:sequence>
              <xs:element name="property" type="scorePropertyType" minOccurs="0" maxOccurs="unbounded"/>
          </xs:sequence>
          <xs:attribute name="name" type="xs:string" use="required"/>
     </xs:complexType>
     
     <xs:complexType name="scorePropertyType">
        <xs:attribute name="name" type="xs:string" use="required"/>
        <xs:attribute name="value" type="xs:string" use="required"/>
    </xs:complexType>	  
</xs:schema>

=== ebi-uniprot/uniprot-core/xml-parser/src/test/resources/proteome/proteome_example.xml
<?xml version="1.0" encoding="UTF-8"?>
<proteomes xmlns="http://uniprot.org/uniprot"
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:schemaLocation="http://uniprot.org/uniprot http://www.uniprot.org/support/docs/proteome.xsd">
<proteome xmlns="http://uniprot.org/uniprot">
    <upid>UP000000718</upid>
    <description>Thermodesulfovibrio yellowstonii (strain ATCC 51303 / DSM 11347 / YP87) is a thermophilic sulfate-reducing bacterium isolated from a thermal vent in Yellowstone Lake in Wyoming, USA. It has the ability to use sulfate, thiosulfate, and sulfite as terminal electron acceptors. Pyruvate can support fermentative growth.</description>
    <taxonomy>289376</taxonomy>
    <modified>2020-10-17Z</modified>
    <isReferenceProteome>true</isReferenceProteome>
    <isRepresentativeProteome>true</isRepresentativeProteome>
    <strain>ATCC 51303 / DSM 11347 / YP87</strain>
    <genomeAssembly>
        <genomeAssemblySource>ENA/EMBL</genomeAssemblySource>
        <genomeAssembly>GCA_000020985.1</genomeAssembly>
        <genomeAssemblyUrl>https://www.ebi.ac.uk/ena/browser/view/GCA_000020985.1</genomeAssemblyUrl>
        <genomeRepresentation>full</genomeRepresentation>
    </genomeAssembly>
    <genomeAnnotation>
        <genomeAnnotationSource>ENA/EMBL</genomeAnnotationSource>
        <genomeAnnotationUrl>https://www.ebi.ac.uk/ena/browser/view/GCA_000020985.1</genomeAnnotationUrl>
    </genomeAnnotation>
    <component name="Chromosome">
        <description>Thermodesulfovibrio yellowstonii DSM 11347</description>
        <biosampleId>SAMN02603929</biosampleId>
        <genomeAccession>CP001147</genomeAccession>
        <genomeAnnotation>
            <genomeAnnotationSource>ENA/EMBL</genomeAnnotationSource>
        </genomeAnnotation>
    </component>
    <reference>
        <citation type="submission" date="2008-08" first="0" last="0" db="EMBL/GenBank/DDBJ databases">
            <title>The complete genome sequence of Thermodesulfovibrio yellowstonii strain ATCC 51303 / DSM 11347 / YP87.</title>
            <authorList>
                <person name="Dodson R.J."/>
                <person name="Durkin A.S."/>
                <person name="Wu M."/>
                <person name="Eisen J."/>
                <person name="Sutton G."/>
            </authorList>
        </citation>
    </reference>
    <reference>
        <citation type="journal article" date="2015" name="Genome Announc" volume="3" first="0" last="0">
            <title>Genome Sequence of the Sulfate-Reducing Thermophilic Bacterium Thermodesulfovibrio yellowstonii Strain DSM 11347T (Phylum Nitrospirae).</title>
            <authorList>
                <person name="Bhatnagar S."/>
                <person name="Badger J.H."/>
                <person name="Madupu R."/>
                <person name="Khouri H.M."/>
                <person name="O'Connor E.M."/>
                <person name="Robb F.T."/>
                <person name="Ward N.L."/>
                <person name="Eisen J.A."/>
            </authorList>
            <dbReference type="PubMed" id="25635016"/>
        </citation>
    </reference>
    <annotationScore normalizedAnnotationScore="2"/>
    <scores name="busco">
        <property name="fragmented" value="3"/>
        <property name="lineage" value="bacteria_odb10"/>
        <property name="missing" value="4"/>
        <property name="completedSingle" value="111"/>
        <property name="completed" value="117"/>
        <property name="total" value="124"/>
        <property name="completedDuplicated" value="6"/>
        <property name="score" value="96"/>
    </scores>
    <scores name="cpd">
        <property name="averageCds" value="3274"/>
        <property name="status" value="Standard"/>
        <property name="confidence" value="0"/>
        <property name="proteomeCount" value="25"/>
        <property name="stdCdss" value="1166.2682710251531"/>
    </scores>
</proteome>
<proteome xmlns="http://uniprot.org/uniprot">
    <upid>UP000006687</upid>
    <taxonomy>11049</taxonomy>
    <modified>2020-10-18Z</modified>
    <isReferenceProteome>true</isReferenceProteome>
    <isRepresentativeProteome>true</isRepresentativeProteome>
    <strain>Lelystad</strain>
    <genomeAssembly>
        <genomeAssemblySource>ENA/EMBL</genomeAssemblySource>
        <genomeAssembly>GCA_003971765.1</genomeAssembly>
        <genomeAssemblyUrl>https://www.ebi.ac.uk/ena/browser/view/GCA_003971765.1</genomeAssemblyUrl>
        <genomeRepresentation>full</genomeRepresentation>
    </genomeAssembly>
    <genomeAnnotation>
        <genomeAnnotationSource>ENA/EMBL</genomeAnnotationSource>
        <genomeAnnotationUrl>https://www.ebi.ac.uk/ena/browser/view/GCA_003971765.1</genomeAnnotationUrl>
    </genomeAnnotation>
    <component name="Genome">
        <description>Lelystad virus</description>
        <genomeAccession>M96262</genomeAccession>
        <genomeAnnotation>
            <genomeAnnotationSource>ENA/EMBL</genomeAnnotationSource>
        </genomeAnnotation>
    </component>
    <reference>
        <citation type="journal article" date="1993" name="Virology" volume="192" first="62" last="72">
            <title>Lelystad virus, the causative agent of porcine epidemic abortion and respiratory syndrome (PEARS), is related to LDV and EAV.</title>
            <authorList>
                <person name="Meulenberg J.J."/>
                <person name="Hulst M.M."/>
                <person name="de Meijer E.J."/>
                <person name="Moonen P.L."/>
                <person name="den Besten A."/>
                <person name="de Kluyver E.P."/>
                <person name="Wensvoort G."/>
                <person name="Moormann R.J."/>
            </authorList>
            <dbReference type="PubMed" id="8517032"/>
            <dbReference type="DOI" id="10.1006/viro.1993.1008"/>
        </citation>
    </reference>
    <annotationScore normalizedAnnotationScore="5"/>
    <scores name="cpd">
        <property name="averageCds" value="9"/>
        <property name="status" value="Standard"/>
        <property name="confidence" value="-1"/>
        <property name="proteomeCount" value="5"/>
        <property name="stdCdss" value="0.7483314773547883"/>
    </scores>
</proteome>
<proteome xmlns="http://uniprot.org/uniprot">
    <upid>UP000029766</upid>
    <taxonomy>60714</taxonomy>
    <modified>2020-10-17Z</modified>
    <isReferenceProteome>true</isReferenceProteome>
    <isRepresentativeProteome>true</isRepresentativeProteome>
    <genomeAssembly>
        <genomeAssemblySource>ENA/EMBL</genomeAssemblySource>
        <genomeAssembly>GCA_000859945.1</genomeAssembly>
        <genomeAssemblyUrl>https://www.ebi.ac.uk/ena/browser/view/GCA_000859945.1</genomeAssemblyUrl>
        <genomeRepresentation>full</genomeRepresentation>
    </genomeAssembly>
    <genomeAnnotation>
        <genomeAnnotationSource>ENA/EMBL</genomeAnnotationSource>
        <genomeAnnotationUrl>https://www.ebi.ac.uk/ena/browser/view/GCA_000859945.1</genomeAnnotationUrl>
    </genomeAnnotation>
    <component name="Genome">
        <description>Galinsoga mosaic virus</description>
        <genomeAccession>Y13463</genomeAccession>
        <genomeAnnotation>
            <genomeAnnotationSource>ENA/EMBL</genomeAnnotationSource>
        </genomeAnnotation>
    </component>
    <reference>
        <citation type="journal article" date="1998" name="Arch. Virol." volume="143" first="173" last="180">
            <title>Molecular cloning and complete nucleotide sequence of galinsoga mosaic virus genomic RNA.</title>
            <authorList>
                <person name="Ciuffreda P."/>
                <person name="Rubino L."/>
                <person name="Russo M."/>
            </authorList>
            <dbReference type="PubMed" id="9505975"/>
            <dbReference type="DOI" id="10.1007/s007050050277"/>
        </citation>
    </reference>
    <annotationScore normalizedAnnotationScore="2"/>
    <scores name="cpd">
        <property name="averageCds" value="5"/>
        <property name="status" value="Standard"/>
        <property name="confidence" value="1"/>
        <property name="proteomeCount" value="65"/>
        <property name="stdCdss" value="1.3700084222088114"/>
    </scores>
</proteome>
<proteome xmlns="http://uniprot.org/uniprot">
    <upid>UP000164653</upid>
    <taxonomy>1076255</taxonomy>
    <modified>2020-10-17Z</modified>
    <isReferenceProteome>true</isReferenceProteome>
    <isRepresentativeProteome>true</isRepresentativeProteome>
    <genomeAssembly>
        <genomeAssemblySource>ENA/EMBL</genomeAssemblySource>
        <genomeAssembly>GCA_000892975.1</genomeAssembly>
        <genomeAssemblyUrl>https://www.ebi.ac.uk/ena/browser/view/GCA_000892975.1</genomeAssemblyUrl>
        <genomeRepresentation>full</genomeRepresentation>
    </genomeAssembly>
    <genomeAnnotation>
        <genomeAnnotationSource>ENA/EMBL</genomeAnnotationSource>
        <genomeAnnotationUrl>https://www.ebi.ac.uk/ena/browser/view/GCA_000892975.1</genomeAnnotationUrl>
    </genomeAnnotation>
    <component name="Genome">
        <description>Yoka poxvirus strain DakArB 4268</description>
        <genomeAccession>HQ849551</genomeAccession>
        <genomeAnnotation>
            <genomeAnnotationSource>ENA/EMBL</genomeAnnotationSource>
        </genomeAnnotation>
    </component>
    <reference>
        <citation type="journal article" date="2011" name="J. Virol." volume="85" first="10230" last="10238">
            <title>The genome of yoka poxvirus.</title>
            <authorList>
                <person name="Zhao G."/>
                <person name="Droit L."/>
                <person name="Tesh R.B."/>
                <person name="Popov V.L."/>
                <person name="Little N.S."/>
                <person name="Upton C."/>
                <person name="Virgin H.W."/>
                <person name="Wang D."/>
            </authorList>
